#!/usr/bin/env bash
# Grand Prix Legends Linux
# ## Desc:
#   Creates wine prefix, mounts iso, downloads and runs the GPL, GEM+ and  Visual Basic runtime installers
# ## Works on:
#   - Ubuntu
#   - Maybe Debian/Ubuntu derivatives. try it and let me know
#   - MacOS
#   - WSL (partially)
# ## Tested on:
#   - Ubuntu 20.4
#   - MacOS Monterrey 12.3.1
#   - Windows 10 Wsl Ubuntu 20.4
# ## Requires:
#    - bash 'on mac may require `brew install bash`'
#    - wget
#    - wine
#    - shasum
#    - udisksctl
#    - file
#    - grep
#    - [innoextract](https://constexpr.org/innoextract/)
# ## Downloads:
#    - GrandPrixLegends.iso from archive.org
#    - gplinstall_beta_1.08.exe from  grandprixlegends.info
#    - GEMPackage_2.5.0.32.exe from gem.grandprixlegends.info
#    - Visual Basic runtime from vb-paradise.de

# ## Notes:
#   - on 'wsl' you will need get display working, see [gwsl](https://opticos.github.io/gwsl/)
#   - uninstall doesn't uninstall but nukes the wine prefix

# ### TODO:
#   - switches: NOCHECKSUM
#   - switch: --info, display installation details
#   - Create GEM+ shortcuts when unpacking instead of installing
# Meta
VERSION=0.0.1
_filename=$(basename $0)
URL="https://github.com/D10221/$_filename"
SRC="https://raw.githubusercontent.com/D10221/$_filename/main/$_filename"
#
# debug
# Set debug to glob * to see all , or enable by func name
#
debug() {
    local caller="${FUNCNAME[1]}" # caller function name
    case "$caller" in
    $DEBUG)
        echo -e "\e[35m$_filename/$caller: $@\e[0m" >&2
        ;;
    esac
}
#
# error echoes to stderr
#
error() { echo -e "\e[31m$_filename/${FUNCNAME[1]}: $@\e[0m" >&2; }
#
# warn
#
warn() { echo -e "\e[33m$_filename/${FUNCNAME[1]}: $@\e[0m" >&2; }
#
# info
#
info() { echo -e "\e[32m$_filename/${FUNCNAME[1]}: $@\e[0m" >&2; }
#
debug "GPL_HOME=${GPL_HOME:="$HOME/.local/share/grand-prix-legends"}" # target installation root
debug "CACHE=${CACHE:="$HOME/.cache/grand-prix-legends"}"             # where to save the downloads
# GPL disc ISO
debug "GPL_ISO_URL=${GPL_ISO_URL:="https://archive.org/download/grand-prix-legends/GrandPrixLegends.iso"}"
debug "GPL_ISO=${GPL_ISO:=$CACHE/grand-prix-legends.iso}"
debug "GPL_ISO_SHA=${GPL_ISO_SHA:="082542e01a9e63c914a8f34f77ee306531a2aa13  $GPL_ISO"}"
debug "GPL_ISO_MNT_POINT=${GPL_ISO_MNT_POINT:="/mnt/$(basename $GPL_ISO)"}" # Global mounting point, to use by 'mount', NOT by 'udisksctl'
debug "GPL_ISO_LABEL=${GPL_ISO_LABEL:="GPL"}"
# GPL installer
debug "GPL_INSTALLER_URL=${GPL_INSTALLER_URL:="http://gem.grandprixlegends.info/gplinstall_beta_1.08.exe"}"
debug "GPL_INSTALLER_EXE=${GPL_INSTALLER_EXE:="$CACHE/gplinstall_beta_1.08.exe"}"
debug "GPL_INSTALLER_EXE_SHASUM=${GPL_INSTALLER_EXE_SHASUM:="5223d8e8c577ec4504fc8c9491b03c61710af263  $GPL_INSTALLER_EXE"}"
# GEM+ Installer
debug "GEM_PACKAGE_URL=${GEM_PACKAGE_URL:="http://gem.grandprixlegends.info/GEM/GEMPackage_2.5.0.32.exe"}"
debug "GEM_PACKAGE_EXE=${GEM_PACKAGE_EXE:="$CACHE/GEMPackage_2.5.0.32.exe"}"
debug "GEM_PACKAGE_EXE_SHA=${GEM_PACKAGE_EXE_SHA:="e8ce456a6db5c2440cb0501accc553730e2ed321  $GEM_PACKAGE_EXE"}"
# VB Community Runtime 1.00
debug "VB_RUNTIME_URL=${VB_RUNTIME_URL:='https://www.vb-paradise.de/index.php/Attachment/27536-vbcrt-zip/?s=a4f2f3891cbdcc314f7a2a2dd5b5338e22d42441'}"
debug "VB_RUNTIME_ZIP=${VB_RUNTIME_ZIP:="$CACHE/VBCommunityRuntime1.00.zip"}"
debug "VB_RUNTIME_ZIP_SHA=${VB_RUNTIME_ZIP_SHA:="eb2c4ecf6057c1b9c27e236b63511785da1d89b0  $VB_RUNTIME_ZIP"}"
debug "VB_RUNTIME_EXE=${VB_RUNTIME_EXE:="$CACHE/VB Community Runtime 1.00.exe"}"
# wine
debug "WINE=${WINE:="$(which wine)"}"
debug "WINEPREFIX=${WINEPREFIX:="$GPL_HOME/pfx"}"
debug "WIN_VERSION=${WIN_VERSION:="win7"}"
DRIVE_C="$WINEPREFIX/drive_c"
# OSTYPE
OS_LINUX='linux'
OS_DARWIN='darwin'
OS_WSL='wsl'
OS=''
case "$OSTYPE" in
linux*)
    # linux variants
    if [ ! -z "$WSL_DISTRO_NAME" ] || [[ $(uname -r) =~ "-microsoft-" ]]; then
        OS=$OS_WSL
    else
        OS=$OS_LINUX
    fi
    ;;
darwin*)
    OS=$OS_DARWIN
    ;;
*)
    echo "OSTYPE $OSTYPE Not Implemented" >&2
    exit 1
    ;;
esac
# WSL
if [ $OS == $OS_WSL ]; then
    debug "WSLDRIVE=${WSLDRIVE:="d"}"
fi
#
# Download url
# creates target directory
# args:
#   $1  'file' local name, full path
#   $2  'url'
#
download() {
    if [ ! -f "$1" ]; then
        mkdir -p "$(dirname $1)"
        debug "Downloading $2 as $1"
        return $(wget $2 -O "$1")
    fi
    return 0
}
#
# Args:
#   $1  'file'
#   $2  'shasum sha'
#
verify() {
    if [ -z "$2" ]; then
        return 0 # disabled
    fi
    local actual=""
    if [ ! -z "$(which shasum)" ]; then
        actual="$(shasum $1)"
        expected=$2
    else
        error "Can't find shasum to verify $1"
        return 1
    fi
    if [ "$actual" != "$expected" ]; then
        debug "Expected $expected"
        debug "Actual   $actual"
        error "Bad hash: $(basename $1)"
        return 1
    fi
    return 0
}
#
# try find backing file used by udisksctl for device
# Args:
#   $1 'label'
# Returns:
#   string or error
#
udisksctl:info:BackingFile() {
    local UDISKSCTL_INFO_BACKING_FILE=$(udisksctl info -b "/dev/disk/by-label/$1" | grep BackingFile)
    local r="\s+BackingFile:\s+(.*)"
    if [[ "$UDISKSCTL_INFO_BACKING_FILE" =~ $r ]]; then
        echo "${BASH_REMATCH[1]}"
    else
        return 1
    fi
}
UNMOUNT=0
#
# mount ISO without sudo
# Args:
#   $1  'ISO'
#   $2  'LABEL'
#
Mount:udisksctl() {
    if [[ $NOUSERMOUNT -eq 1 ]]; then # debug
        return 1                      # not unmounted
    fi
    # get the device backing file
    local USER_MOUNT_BACKING_FILE="$(udisksctl:info:BackingFile $2)"
    # already mounted?
    if [ -f "$USER_MOUNT_BACKING_FILE" ] && [ $USER_MOUNT_BACKING_FILE == $1 ]; then
        UNMOUNT=0
        return 0
    elif udisksctl loop-setup -f $1; then
        UNMOUNT=1
        debug "Mounted '$1'"
        return 0 # mounted
    else
        return 1 # failed
    fi
}
#
# Args:
#       $1  'Drive Letter'
#
wsl:drive:valid() {
    if [ -z "$1" ]; then
        error "wsldrive is required to mount $(basename $GPL_ISO), relaunch with --nomount OR --wsldrive='<drive>', see --help for more"
        return 1 # failed
    fi
    if ! [[ "$1" =~ ^[a-zA-Z]$ ]]; then
        error "'$1' is not a valid drive letter, see --help for more"
        return 1 # failed
    fi
}
#
# mount ISO with 'mount' , needs root
# Args:
#   $1  'GPL_ISO'
#   $2  'GPL_ISO_MNT_POINT'
#   $3  'WSLDRIVE'
#
Mount() {
    if [[ $NOROOTMOUNT -eq 1 ]]; then # debug
        return 1                      # failed
    fi
    # if not mounted
    if [ -z "$(mount | grep $(basename "$1"))" ]; then
        info "Mounting '$(basename "$1")' into '$2'"
        if [ $OS == $OS_WSL ]; then
            # Mounting in WSL is different
            if ! wsl:drive:valid $3; then
                warn "wsl drive '$3' is not valid, using 'd:'"
                return 1 # failed
            fi
            local WINE_DRIVE="$3"
            if ! wsl:drive:valid "$3"; then
                warn "WINE_DRIVE '$3' is not valid, using '$3'"
                WINE_DRIVE="d"
            fi
            if sudo mkdir -p "$2" &&
                sudo mount -t drvfs "$WINE_DRIVE:" "$2"; then
                # create simlink in pfx/dosdevices/d:
                if ln -s "$2" "$WINEPREFIX/dosdevices/$WINE_DRIVE:"; then # or wine doesn't see it
                    UNMOUNT=1                                             # OK, flag unmount
                fi
            else
                return 1 # failed
            fi
        else
            # mounting on linux
            if [ ! -d "$2" ]; then
                if ! mkdir -p "$2"; then
                    debug "mount point '$2' is not a directory .. trying with sudo"
                    if ! sudo mkdir -p "$2"; then
                        error "failed to create mount point '$2'"
                        return 1
                    fi
                fi
            fi
            if ! mount -o ro,loop "$1" "$2"; then # try mount
                debug "trying to mount '$1' with sudo"
                if ! sudo mount -o ro,loop "$1" "$2"; then # try mount with superuser
                    error "Failed to mount '$1'"
                    return 1
                fi
                #OK
                debug "mounted $1"
                UNMOUNT=1 # flag unmountMount
            fi
        fi
    else
        return 0 # mounted
    fi
}
#
# try un mount iso if it was mounted
# by $OS
# Args:
#   $1  'ISO'
#   $2  'Label'
#   $3  'GPL_ISO_MNT_POINT'
#   $4  'WSLDRIVE'
#
Mount:try() {
    if [[ $NOMOUNT -eq 1 ]]; then
        # --nomount?
        return 0
    fi
    debug "Mounting '$(basename $1)'"
    # by os
    case $OS in
    $OS_DARWIN)
        if hdiutil mount "$1"; then
            debug "$(basename "$1") '$OS' 'Mounted' by hdiutil"
            UNMOUNT=1
            return 0
        fi
        ;;
    $OS_LINUX)
        # try to mount with udisksctl in user space
        if Mount:udisksctl "$1" "$2"; then
            return 0
        fi
        # mount using mount, may need root
        if Mount "$1" "$3" "$4"; then
            return 0
        fi
        ;;
    $OS_WSL)
        if Mount "$1" "$3" "$4"; then
            debug "$(basename "$1") '$OS' 'Mounted' by 'Mount'"
            UNMOUNT=1
            return 0
        fi
        ;;
    *)
        error "Mount '$(basename "$1")' on '$OS' in not implemented"
        return 1 #failed
        ;;
    esac
    # Failed
    msg="'$OS': Unable to mount '$(basename $1)'\n"
    msg+=" You will need to mount '$1'\n"
    msg+=" Or load the Disc your self.\n"
    msg+=" Relaunch with '--nomount' to skip mounting '$1'"
    error "$msg"
    return 1
}
#
# unmount ISO without sudo
# Args:
#   $1  'label'
#
Unmount:udisksctl() {
    if [[ $NOUSERMOUNT -eq 1 ]]; then
        return 1
    fi
    if ! udisksctl unmount -b "/dev/disk/by-label/$1"; then
        return 1
    fi
    debug "unmounted '$1"
}
#
# unmount mount point , needs root
# Args:
#   $1  'GPL_ISO_MNT_POINT'
#
Unmount() {
    debug "Begin Unmount GPL_ISO_MNT_POINT='$1'"
    if ! [[ $UNMOUNT -eq 1 ]]; then
        return 0 # not mounted
    fi
    if ! umount "$1"; then
        if ! sudo umount "$1"; then
            error "'$SUDO umount $1' failed"
            return 1 # fail
        fi
    fi
    debug "Unmounted $1"
}
#
# try un unmount iso if it was mounted
# by $OS
# Args:
#   $1  'ISO'
#   $2  'label'
#   $3  'GPL_ISO_MNT_POINT'
#
Unmount:try() {
    if [[ $UNMOUNT -eq 1 ]]; then
        debug "unmounting $(basename "$1")"
        if [ $OS == $OS_DARWIN ]; then
            hdiutil unmount /Volumes/$2
            # debug "'$OS' '$(basename $GPL_ISO)' unmounted by 'hdiutil'"
        elif [ $OS == $OS_LINUX ]; then
            if Unmount:udisksctl "$2"; then
                return 0
            fi
            if Unmount "$3"; then
                return 0
            fi
            return 1
        elif [ $OS == $OS_WSL ]; then
            if ! Unmount "$3"; then
                if ! rm "$WINE_DRIVE_PATH"; then
                    warn "Failed to remove '$WINE_DRIVE_PATH'"
                    return 1 # failed
                fi
            fi
            debug "'$OS' '$(basename "$1")' unmounted by 'unmount'"
        else
            error "Unmounting $1 on $OS is not implemented"
        fi
    fi
}
#
# Download and verify
# Args:
#   $1  'file' local name, full path
#   $2  'url'
#   $3  'sha'
#
get() {
    if ! download $1 $2; then
        error "failed to download '$(basename $1)' from '$2'"
        return 1
    fi
    # verify
    if ! verify $1 "$3"; then
        error "failed to verify '$(basename $1)'"
        return 1
    fi
}
#
# Installs GEM+
# Args:
#   none
# Options:
#   -i  Use/run the installer
#   -u  Unpack the installer
#   -h  show usage
#
install:gem() {
    # show usage
    install:gem:usage() {
        echo "Installs GEM+"
        echo "$_filename install gem [options] [args]"
        echo "Options: "
        echo " -i Runs GEM+ installer"
        echo " -u Unpacks GEM+ installer into c:\GPLSecrets , find GEM+ in c:\GPLSecrets\app"
        echo " -h Shows this"
    }
    while getopts ":iuh" arg; do
        case ${arg} in
        i)
            debug "Running GEM+ installer"
            # get GEM installer  download if not in cache
            if get "$GEM_PACKAGE_EXE" "$GEM_PACKAGE_URL" "$GEM_PACKAGE_EXE_SHA"; then
                debug "Runnig GEM+ installer"
                if runExe "$GEM_PACKAGE_EXE"; then
                    GEM_INSTALLED=1
                    debug "installed GEM+?"
                else
                    debug "failed to install GEM+"
                fi
            fi
            ;;
        u)
            # Unpack GEM+ into drive c:\
            # prefix breaks when installing GEM+ with the installer
            if get "$GEM_PACKAGE_EXE" "$GEM_PACKAGE_URL" "$GEM_PACKAGE_EXE_SHA"; then
                # get GEM+ installer  download if not in cache
                if [ ! -d "$DRIVE_C" ]; then
                    if ! createPrefix; then
                        debug "Failed to create prefix: $WINEPREFIX"
                        return 1
                    fi
                fi
                if [ -z "$(which innoextract)" ]; then
                    error "Can't find 'innoextract', install innoextract and try again"
                    return 1

                fi
                local GPLSecrets="$DRIVE_C/GPLSecrets"               
                if ! innoextract "$GEM_PACKAGE_EXE" -d "$GPLSecrets" -s; then
                    error "failed to extract '$GEM_PACKAGE_EXE'"
                    return 1
                fi
                debug "extracted $GEM_PACKAGE_EXE into '$GPLSecrets'"             
                if ! cp "$GPLSecrets/syswow64/GPLPatchDLL.dll" "$DRIVE_C/windows/syswow64/"; then
                    warn "Failed to move GPLPatchDLL.dll to windows/syswow64"
                    warn "GEMP2.exe might not work"
                fi
                info "Extracted $GEM_PACKAGE_EXE into $GPLSecrets"
            fi
            ;;
        h)
            install:gem:usage
            ;;
        *)
            error "Unknown option '$OPTARG'"
            return 1
            ;;
        esac
    done
    if [[ $# -lt 1 ]]; then
        error "Expected options"
        install:gem:usage
        return 1
    fi
}
#
# Install GPL
#
install:gpl() {
    # get GPL ISO installer, download if not in cache
    if ! get "$GPL_ISO" "$GPL_ISO_URL" "$GPL_ISO_SHA"; then
        return 1
    fi
    # get GPL installer, download if not in cache
    if ! get "$GPL_INSTALLER_EXE" "$GPL_INSTALLER_URL" "$GPL_INSTALLER_EXE_SHASUM"; then
        return 1
    fi
    # try mount ISO, required by GPL installer
    local mounted=0
    if Mount:try "$GPL_ISO" "$GPL_ISO_LABEL" "$GPL_ISO_MNT_POINT" "$WSLDRIVE"; then
        mounted=1
    fi
    #  GPL installer needs the CD
    if [[ $mounted -eq 1 ]]; then
        debug "Running GPL installer"
        if runExe "$GPL_INSTALLER_EXE"; then
            GPL_INSTALLED=1
            debug "installed GPL"
        else
            error "Failed to install GPL"
        fi
    else
        error "Can't install GPL"
    fi
    # try Unmount ISO
    if ! Unmount:try "$GPL_ISO" "$GPL_ISO_LABEL" "$GPL_ISO_MNT_POINT"; then
        error "Failed to unmount "$GPL_ISO_LABEL" "$GPL_ISO""
    fi
}
#
# Install Visual Basic Runtime
#
install:vbr() {
    if get "$VB_RUNTIME_ZIP" "$VB_RUNTIME_URL" "$VB_RUNTIME_ZIP_SHA"; then
        if Unzip "$VB_RUNTIME_ZIP" "$CACHE"; then
            # unzipped to cache
            debug "Running VB Runtime Installer"
            if runExe "$VB_RUNTIME_EXE"; then
                VB_RUNTIME_INSTALLED=1
                info "VB Runtime Installed"
            else
                error "Can't install VB Runtime"
            fi
        else
            debug "can't unzip 'VB Runtime'"
        fi
    fi
}
#
# Install
# Usage:
#   Install [options] [...selection]
# Opts:
#   -y 'yes' accepts all options , not implemented
# Example
#  'install # gpl'
#  'install gpl gem vbr'
#
Install() {
    local YES=0
    while getopts ":h" arg; do
        case ${arg} in
        h)
            echo "install [options] [target]"
            echo "Options: -h shows this"
            echo "Targets: gpl gem vbr"
            ;;
        *)
            error "Unknown option '$OPTARG'"
            return 1
            ;;
        esac
    done
    if [[ $# -lt 1 ]]; then
        error "Expected args"
        return 1
    else
        for a in $@; do
            case "$a" in
            -*) ;; # skip options
            gpl)
                shift
                install:gpl $@
                ;;
            gem)
                shift
                install:gem $@
                ;;
            vbr)
                shift
                install:vbr $@
                ;;
            *)
                error "Don't know how to install '$a'"
                exit 1
                ;;
            esac
        done
    fi
}
#
# Args:
#   $1  'zip file'
#   $2  'target directory'
#
Unzip() {
    if [ ! -f "$(which unzip)" ]; then
        error "Can't find 'unzip'"
    fi
    debug "Unzipping '$1' to '$2'"
    unzip -oq "$1" -d "$2"
    return $?
}
#
# get basename without ext
# ex: basenameNoExtension 'file.zip' '.zip'
#
basenameNoExtension() {
    echo $(basename "$1") | tr -d "$2"
}
#
#
#
createPrefix() {
    if ! runWithPrefix wine winecfg -v "$WIN_VERSION"; then
        return 1
    else
        debug "Created prefix as '$WIN_VERSION'"
    fi
}
#
# Run exe on WINEPREFIX, log to ~/<exe-name>.log
# Args:
#   $1 file
#
runExe() {
    if [ ! -f "$WINE" ]; then
        error "can't find wine, get wine on the \$PATH and try again"
        return 1
    fi
    if ! mkdir -p "$WINEPREFIX" || ! WINEPREFIX="$WINEPREFIX" $WINE "$1" >~/"$(basename "$1").log" 2>&1; then
        return 1
    fi
}
#
# Run cmd on WINEPREFIX env
#
runWithPrefix() {
    if [ ! -f "$WINE" ]; then
        error "can't find wine, get wine on the \$PATH and try again"
        return 1
    fi
    if ! mkdir -p "$WINEPREFIX" || ! WINEPREFIX="$WINEPREFIX" $@; then
        error "Failed to run '$@' on WINEPREFIX="$WINEPREFIX""
        return 1
    fi
}
#
# Args:
#   $1  'label'
#   $2  'target'
#
remove() {
    warn "Remove '$1' '$2'"
    read -p "Cannot be undone (y/n)? " u
    case $u in
    y)
        rm -rf "$2"
        return $?
        ;;
    n)
        info "Cancelled."
        ;;
    *)
        error "Unknown option '$u', Cancelled!"
        return 1
        ;;
    esac
}
#
# Uninstall GPL and remove prefix
# Args:
#   '$@' [gpl,gem]
#
uninstall() {
    warn "this tool doesn't uninstall but removes the target"
    if [[ $# -lt 1 ]]; then
        error "expected args"
        return 1
    else
        for a in $@; do
            case "$a" in
            gpl)
                local GPL_EXE="$WINEPREFIX/drive_c/Sierra/GPL/gpl.exe"
                local DIR=$(dirname $GPL_EXE)
                remove 'GPL' "$DIR"
                ;;

            gem)
                local GEM_EXE="$WINEPREFIX/drive_c/GPLSecrets/GEM+/GEMP2.exe"
                local DIR=$(dirname $GEM_EXE)
                remove 'GEM+' "$DIR"
                ;;          
            pfx)
                remove 'prefix' "$WINEPREFIX"
                ;;
            cache)
                remove 'cache' "$CACHE"
                ;;
            *)
                error "Can't remove '$a'"
                return 1
                ;;
            esac
        done
    fi

}
#
# open WINEPREFIX/?
#
Open() {
    if [ $OS == $OS_DARWIN ]; then
        open $WINEPREFIX/"$1"
    else
        xdg-open $WINEPREFIX/"$1"
    fi
}
#
#
#
Launch() {
    case "$1" in
    gpl)
        runWithPrefix "$WINE" start 'c:\sierra\GPL\gpl.exe' /d 'c:\sierra\GPL' # /wait
        ;;
    gpl67)
        runWithPrefix "$WINE" start 'c:\sierra\GPL\gplc67.exe' /d 'c:\sierra\GPL' # /wait
        ;;
    gem+)
        # TODO: use find -> winepath ?
        if ! runWithPrefix "$WINE" start 'c:\GPLSecrets\GEM+\GEMP2.exe' /d 'c:\sierra\GPL'; then
            if ! runWithPrefix "$WINE" start 'c:\GPLSecrets\app\GEM+\GEMP2.exe' /d 'c:\sierra\GPL'; then
                error "Can't find or open GEMP2.exe"
            fi
        fi
        ;;
    *)
        error "Don't how to open '$1'"
        ;;
    esac
}
#
# Args:
#   $1  'option' ex, 'x=1'
# Returns:
#   $2  'value'
#
optionValue() {
    local r="\w+=(.*)"
    if [[ "$1" =~ $r ]]; then
        echo "${BASH_REMATCH[1]}"
    else
        return 1
    fi
}
#
# show usage
#
usage() {
    echo "Grand Prix Legends wine Installer v$VERSION"
    echo "Usage: '$_filename [verb] [options]'"
    echo "Verbs: "
    echo "  install [options?] [target]?   'run GPL installers'"
    echo "      options:"
    echo "          -h help"
    echo "      target:"
    echo "          gpl gem vbr"
    echo "      example:"
    echo "          \$gpli install -r gpl # REINSTALL gpl"
    echo "          \$gpli install -r gpl gem vbr # reinstall gpl gem -u vbr"
    echo "      Notes:   gem target has options see install gem -h for details"
    echo "  uninstall [options?] 'remove GPL,GEM and wine Prefix'"
    echo "      options: "
    echo "          'gpl'   remove 'c:\Sierra\gpl'"
    echo "          'geml'  remove 'c:\Sierra\gpl'"
    echo "          'pfx'      remove 'prefix' (default)"
    echo "  run                   \"run something in gpl's WINEPREFIX\""
    echo "      example:    '\$$_filename run wine winecfg'"
    echo "  wine                  \"run wine 'something' gpl's WINEPREFIX\""
    echo "      example:    '\$$_filename wine winecfg'"
    echo "  open"
    echo "      example: '\$$_filename open' # opens \$WINEPREFIX"
    echo "      example: '\$$_filename open dirve_c ' # opens \$WINEPREFIX/drive_c"
    echo "  launch"
    echo "      example: '\$$_filename launch gpl'  # starts wine 'c:\Sierra\GPL\gpl.exe'"
    echo "      example: '\$$_filename launch gem+' # starts wine 'c:\GPLSecrets\GEM+\GEMP2.exe'"
    echo ""
    echo "Options:"
    echo "  -h --help      'Show this'"
    echo "  -v --version   'Show '$_filename' version'"
    echo "  --nomount      'Do not try to mount ISO'"
    if [ $OS == $OS_WSL ]; then
        echo "  --wsldrive='<drive>'"
        echo "      desc:   'drive letter to mount in wsl environment'"
        echo "              'required on WSL'"
        echo "      <drive>: [az-AZ]"
        echo "      example '--wsldrive=d'"
    fi
    echo ""
    echo "Vars:"
    echo " NOMOUNT         'Do not try to mount ISO'"
    echo " NOUSERMOUNT     'Do not try to mount ISO in userspace'"
    echo " NOROOTMOUNT     'Do not try to mount ISO if requires root access"
    echo " DEBUG           'show debug info'"
    echo "                  example '\$ DEBUG='*' ./gpli.local install'"
    if [ $OS == $OS_WSL ]; then
        echo " WSLDRIVE        'show debug info'"
        echo "    desc:        'drive letter to mount in wsl environment'"
        echo "                 'required to install GPL on WSL'"
        echo "      <drive>: [az-AZ]"
        echo "                  example '\$ WSLDRIVE=d ./gpli.local install'"
    fi
}
#
if [[ $# -lt 1 ]]; then
    usage
    exit 1
fi
#
# Exec Opts
#
option() {
    case $1 in
    help)
        OPTKEY='h'
        usage
        exit
        ;;
    version)
        OPTKEY='v'
        echo "v$VERSION"
        exit
        ;;
    nomount)
        NOMOUNT=1
        ;;
    wsldrive)
        WSLDRIVE="$2"
        if ! wsl:drive:valid $WSLDRIVE; then
            exit 1
        fi
        ;;
    *)
        error "Invalid option '$1'"
        exit 1
        ;;
    esac
}
# parse opts
while getopts ":hvu-:" o; do
    case "${o}" in
    -)
        case "${OPTARG}" in
        help)
            option 'help' "$(optionValue $OPTARG)"
            ;;
        version)
            option 'version' "$(optionValue $OPTARG)"
            ;;
        nomount)
            shift
            option 'nomount' "$(optionValue $OPTARG)"
            ;;
        wsldrive=*)
            shift
            option 'wsldrive' "$(optionValue $OPTARG)"
            ;;
        *)
            error "Unknown option --${OPTARG}"
            exit 1
            ;;
        esac
        ;;
    h)
        option "help" "$OPTARG"
        ;;
    v)
        option "version" "$OPTARG"
        ;;
    ?)
        if [ "$OPTERR" != 1 ] || [ "${OPTSPEC:0:1}" = ":" ]; then
            error "bad optiont: '-${OPTARG}'"
        fi
        error "Unknown option -${OPTARG}"
        exit 1
        ;;
    esac
done
# launch verbs
case $1 in
install)
    shift
    if Install "$@"; then
        debug "done"
    else
        error "done with error"
    fi
    ;;
uninstall)
    shift
    uninstall "$@"
    ;;
run)
    shift
    runWithPrefix $@
    ;;
wine)
    shift
    runWithPrefix "$WINE" $@
    ;;
open)
    shift
    Open "$1"
    ;;
launch)
    shift
    Launch "$1"
    ;;
*)
    error "Unkown verb:'$1'"
    exit 1
    ;;
esac
